//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MaestroEntities : DbContext
    {
        public MaestroEntities()
            : base("name=MaestroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_CreateEditCity_Result> sp_CreateEditCity(Nullable<int> cODE, string dESCRIPTION)
        {
            var cODEParameter = cODE.HasValue ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(int));
    
            var dESCRIPTIONParameter = dESCRIPTION != null ?
                new ObjectParameter("DESCRIPTION", dESCRIPTION) :
                new ObjectParameter("DESCRIPTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CreateEditCity_Result>("sp_CreateEditCity", cODEParameter, dESCRIPTIONParameter);
        }
    
        public virtual ObjectResult<sp_CreateEditSeller_Result> sp_CreateEditSeller(Nullable<int> cODE, string nAME, string lAST_NAME, string dOCUMENT, Nullable<int> cITY_ID)
        {
            var cODEParameter = cODE.HasValue ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(int));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var dOCUMENTParameter = dOCUMENT != null ?
                new ObjectParameter("DOCUMENT", dOCUMENT) :
                new ObjectParameter("DOCUMENT", typeof(string));
    
            var cITY_IDParameter = cITY_ID.HasValue ?
                new ObjectParameter("CITY_ID", cITY_ID) :
                new ObjectParameter("CITY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CreateEditSeller_Result>("sp_CreateEditSeller", cODEParameter, nAMEParameter, lAST_NAMEParameter, dOCUMENTParameter, cITY_IDParameter);
        }
    
        public virtual ObjectResult<sp_DeleteCity_Result> sp_DeleteCity(Nullable<int> cODE)
        {
            var cODEParameter = cODE.HasValue ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DeleteCity_Result>("sp_DeleteCity", cODEParameter);
        }
    
        public virtual ObjectResult<sp_DeleteSeller_Result> sp_DeleteSeller(Nullable<int> cODE)
        {
            var cODEParameter = cODE.HasValue ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DeleteSeller_Result>("sp_DeleteSeller", cODEParameter);
        }
    
        public virtual ObjectResult<sp_GetCities_Result> sp_GetCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCities_Result>("sp_GetCities");
        }
    
        public virtual ObjectResult<sp_GetSellers_Result> sp_GetSellers(Nullable<int> s_CODE)
        {
            var s_CODEParameter = s_CODE.HasValue ?
                new ObjectParameter("S_CODE", s_CODE) :
                new ObjectParameter("S_CODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSellers_Result>("sp_GetSellers", s_CODEParameter);
        }
    }
}
